import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import styled from 'styled-components';
import { RiFilter2Line } from 'react-icons/ri';

import { Navbar } from '../../components';
import {
  ProductCategoryContainer,
  ProductCategoryMain,
  ProductCategoryCardContainer,
} from '../../styles/ProductsByCategory';

const ProductCategoryHeader = styled.div`
  width: 100%;
  display: flex;
  justify-content: space-between;
  margin: 30px 0;

  span {
    font-size: 24px;
  }
`;

const FilterButton = styled.button`
  padding: 12px 24px;
  font-weight: 700;
  font-size: 16px;
  border: 1px solid #2c2c2c;
  border-radius: 8px;
  display: flex;
  align-items: center;
  background-color: #fff;
  cursor: pointer;

  &:hover {
    background-color: #f5f5f5;
  }

  svg {
    font-size: 22px;
    margin-right: 12px;
  }
`;

const ProductByCategory: NextPage = () => {
  return (
    <>
      <Navbar page={'productsByCategory'} />
      <ProductCategoryContainer>
        <Head>
          <title>Adidas Online Store</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <ProductCategoryMain>
          <ProductCategoryHeader>
            <span>
              Home <b>/ Adidas Original</b>
            </span>
            <FilterButton>
              <RiFilter2Line />
              Filter & Sort
            </FilterButton>
          </ProductCategoryHeader>
          <ProductCategoryCardContainer></ProductCategoryCardContainer>
        </ProductCategoryMain>
      </ProductCategoryContainer>
    </>
  );
};

export default ProductByCategory;
