import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { Banner, ProductCard } from '../components';
import {
  HomeContainer,
  HomeMain,
  BannerContainer,
  ProductContainer,
} from '../styles/Home';
import { Product, GetProductItems } from '../types/product';

const Home: NextPage<{ products: Product[] }> = ({ products }) => {
  return (
    <HomeContainer>
      <Head>
        <title>Adidas Online Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeMain>
        <BannerContainer id={'banner'}>
          <Banner />
        </BannerContainer>
        <ProductContainer>
          {products.map((product, index) => (
            <ProductCard key={index} product={product} />
          ))}
        </ProductContainer>
      </HomeMain>
    </HomeContainer>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.get(
    'https://asia-southeast1-muze-academy.cloudfunctions.net/products'
  );
  const { items }: GetProductItems = await res.data;

  return {
    props: { products: items },
  };
};

export default Home;
